[package]
name = "myssh"
version = "0.0.1"
edition = "2021"

[dependencies]
cursive = "0.20"
regex = "1"

[profile.release]
debug = false
opt-level = 3
lto = true

[profile.dev]
opt-level = 1              
overflow-checks = false  